/*
 * Facebook Conversions API (for Web)
 *
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: web_signals_integrations@fb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using SoundInTheory.Facebook.ConversionsAPI.Client;
using SoundInTheory.Facebook.ConversionsAPI.Model;

namespace SoundInTheory.Facebook.ConversionsAPI.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SoundInTheory.Facebook.ConversionsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pixelId"></param>
        /// <param name="body">Facebook Conversions API (for Web) post request</param>
        /// <returns>ResponseSuccess</returns>
        ResponseSuccess PixelIdEventsPost (string pixelId, EventRequest body);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SoundInTheory.Facebook.ConversionsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pixelId"></param>
        /// <param name="body">Facebook Conversions API (for Web) post request</param>
        /// <returns>ApiResponse of ResponseSuccess</returns>
        ApiResponse<ResponseSuccess> PixelIdEventsPostWithHttpInfo (string pixelId, EventRequest body);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SoundInTheory.Facebook.ConversionsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pixelId"></param>
        /// <param name="body">Facebook Conversions API (for Web) post request</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ResponseSuccess</returns>
        System.Threading.Tasks.Task<ResponseSuccess> PixelIdEventsPostAsync (string pixelId, EventRequest body, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="SoundInTheory.Facebook.ConversionsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pixelId"></param>
        /// <param name="body">Facebook Conversions API (for Web) post request</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (ResponseSuccess)</returns>
        System.Threading.Tasks.Task<ApiResponse<ResponseSuccess>> PixelIdEventsPostWithHttpInfoAsync (string pixelId, EventRequest body, CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DefaultApi : IDefaultApi
    {
        private SoundInTheory.Facebook.ConversionsAPI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi(String basePath)
        {
            this.Configuration = new SoundInTheory.Facebook.ConversionsAPI.Client.Configuration { BasePath = basePath };

            ExceptionFactory = SoundInTheory.Facebook.ConversionsAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// </summary>
        /// <returns></returns>
        public DefaultApi()
        {
            this.Configuration = SoundInTheory.Facebook.ConversionsAPI.Client.Configuration.Default;

            ExceptionFactory = SoundInTheory.Facebook.ConversionsAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DefaultApi(SoundInTheory.Facebook.ConversionsAPI.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = SoundInTheory.Facebook.ConversionsAPI.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = SoundInTheory.Facebook.ConversionsAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SoundInTheory.Facebook.ConversionsAPI.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SoundInTheory.Facebook.ConversionsAPI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SoundInTheory.Facebook.ConversionsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pixelId"></param>
        /// <param name="body">Facebook Conversions API (for Web) post request</param>
        /// <returns>ResponseSuccess</returns>
        public ResponseSuccess PixelIdEventsPost (string pixelId, EventRequest body)
        {
             ApiResponse<ResponseSuccess> localVarResponse = PixelIdEventsPostWithHttpInfo(pixelId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SoundInTheory.Facebook.ConversionsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pixelId"></param>
        /// <param name="body">Facebook Conversions API (for Web) post request</param>
        /// <returns>ApiResponse of ResponseSuccess</returns>
        public ApiResponse<ResponseSuccess> PixelIdEventsPostWithHttpInfo (string pixelId, EventRequest body)
        {
            // verify the required parameter 'pixelId' is set
            if (pixelId == null)
                throw new ApiException(400, "Missing required parameter 'pixelId' when calling DefaultApi->PixelIdEventsPost");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->PixelIdEventsPost");

            var localVarPath = "/{pixelId}/events";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (pixelId != null) localVarPathParams.Add("pixelId", this.Configuration.ApiClient.ParameterToString(pixelId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (facebook_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("access_token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "access_token", this.Configuration.GetApiKeyWithPrefix("access_token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PixelIdEventsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResponseSuccess>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ResponseSuccess) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResponseSuccess)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SoundInTheory.Facebook.ConversionsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pixelId"></param>
        /// <param name="body">Facebook Conversions API (for Web) post request</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ResponseSuccess</returns>
        public async System.Threading.Tasks.Task<ResponseSuccess> PixelIdEventsPostAsync (string pixelId, EventRequest body, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<ResponseSuccess> localVarResponse = await PixelIdEventsPostWithHttpInfoAsync(pixelId, body, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="SoundInTheory.Facebook.ConversionsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pixelId"></param>
        /// <param name="body">Facebook Conversions API (for Web) post request</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (ResponseSuccess)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ResponseSuccess>> PixelIdEventsPostWithHttpInfoAsync (string pixelId, EventRequest body, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'pixelId' is set
            if (pixelId == null)
                throw new ApiException(400, "Missing required parameter 'pixelId' when calling DefaultApi->PixelIdEventsPost");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->PixelIdEventsPost");

            var localVarPath = "/{pixelId}/events";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (pixelId != null) localVarPathParams.Add("pixelId", this.Configuration.ApiClient.ParameterToString(pixelId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (facebook_api_key) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("access_token")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "access_token", this.Configuration.GetApiKeyWithPrefix("access_token")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PixelIdEventsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ResponseSuccess>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ResponseSuccess) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ResponseSuccess)));
        }

    }
}
