/*
 * Facebook Conversions API (for Web)
 *
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: web_signals_integrations@fb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SoundInTheory.Facebook.ConversionsAPI.Client.OpenAPIDateConverter;

namespace SoundInTheory.Facebook.ConversionsAPI.Model
{
    /// <summary>
    /// ResponseSuccess
    /// </summary>
    [DataContract]
    public partial class ResponseSuccess :  IEquatable<ResponseSuccess>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseSuccess" /> class.
        /// </summary>
        /// <param name="eventsReceived">eventsReceived.</param>
        /// <param name="messages">messages.</param>
        /// <param name="fbtraceId">fbtraceId.</param>
        public ResponseSuccess(int eventsReceived = default(int), List<string> messages = default(List<string>), string fbtraceId = default(string))
        {
            this.EventsReceived = eventsReceived;
            this.Messages = messages;
            this.FbtraceId = fbtraceId;
        }

        /// <summary>
        /// Gets or Sets EventsReceived
        /// </summary>
        [DataMember(Name="events_received", EmitDefaultValue=false)]
        public int EventsReceived { get; set; }

        /// <summary>
        /// Gets or Sets Messages
        /// </summary>
        [DataMember(Name="messages", EmitDefaultValue=false)]
        public List<string> Messages { get; set; }

        /// <summary>
        /// Gets or Sets FbtraceId
        /// </summary>
        [DataMember(Name="fbtrace_id", EmitDefaultValue=false)]
        public string FbtraceId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResponseSuccess {\n");
            sb.Append("  EventsReceived: ").Append(EventsReceived).Append("\n");
            sb.Append("  Messages: ").Append(Messages).Append("\n");
            sb.Append("  FbtraceId: ").Append(FbtraceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ResponseSuccess);
        }

        /// <summary>
        /// Returns true if ResponseSuccess instances are equal
        /// </summary>
        /// <param name="input">Instance of ResponseSuccess to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResponseSuccess input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EventsReceived == input.EventsReceived ||
                    (this.EventsReceived != null &&
                    this.EventsReceived.Equals(input.EventsReceived))
                ) && 
                (
                    this.Messages == input.Messages ||
                    this.Messages != null &&
                    input.Messages != null &&
                    this.Messages.SequenceEqual(input.Messages)
                ) && 
                (
                    this.FbtraceId == input.FbtraceId ||
                    (this.FbtraceId != null &&
                    this.FbtraceId.Equals(input.FbtraceId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EventsReceived != null)
                    hashCode = hashCode * 59 + this.EventsReceived.GetHashCode();
                if (this.Messages != null)
                    hashCode = hashCode * 59 + this.Messages.GetHashCode();
                if (this.FbtraceId != null)
                    hashCode = hashCode * 59 + this.FbtraceId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
