/*
 * Facebook Conversions API (for Web)
 *
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: web_signals_integrations@fb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SoundInTheory.Facebook.ConversionsAPI.Api;
using SoundInTheory.Facebook.ConversionsAPI.Model;
using SoundInTheory.Facebook.ConversionsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SoundInTheory.Facebook.ConversionsAPI.Test
{
    /// <summary>
    ///  Class for testing CustomData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomDataTests
    {
        // TODO uncomment below to declare an instance variable for CustomData
        //private CustomData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomData
            //instance = new CustomData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomData
        /// </summary>
        [Test]
        public void CustomDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CustomData
            //Assert.IsInstanceOf(typeof(CustomData), instance);
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'ContentName'
        /// </summary>
        [Test]
        public void ContentNameTest()
        {
            // TODO unit test for the property 'ContentName'
        }
        /// <summary>
        /// Test the property 'ContentCategory'
        /// </summary>
        [Test]
        public void ContentCategoryTest()
        {
            // TODO unit test for the property 'ContentCategory'
        }
        /// <summary>
        /// Test the property 'ContentIds'
        /// </summary>
        [Test]
        public void ContentIdsTest()
        {
            // TODO unit test for the property 'ContentIds'
        }
        /// <summary>
        /// Test the property 'Contents'
        /// </summary>
        [Test]
        public void ContentsTest()
        {
            // TODO unit test for the property 'Contents'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'PredictedLtv'
        /// </summary>
        [Test]
        public void PredictedLtvTest()
        {
            // TODO unit test for the property 'PredictedLtv'
        }
        /// <summary>
        /// Test the property 'NumItems'
        /// </summary>
        [Test]
        public void NumItemsTest()
        {
            // TODO unit test for the property 'NumItems'
        }
        /// <summary>
        /// Test the property 'SearchString'
        /// </summary>
        [Test]
        public void SearchStringTest()
        {
            // TODO unit test for the property 'SearchString'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
