/*
 * Facebook Conversions API (for Web)
 *
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: web_signals_integrations@fb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SoundInTheory.Facebook.ConversionsAPI.Api;
using SoundInTheory.Facebook.ConversionsAPI.Model;
using SoundInTheory.Facebook.ConversionsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SoundInTheory.Facebook.ConversionsAPI.Test
{
    /// <summary>
    ///  Class for testing ModelEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelEventTests
    {
        // TODO uncomment below to declare an instance variable for ModelEvent
        //private ModelEvent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelEvent
            //instance = new ModelEvent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelEvent
        /// </summary>
        [Test]
        public void ModelEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ModelEvent
            //Assert.IsInstanceOf(typeof(ModelEvent), instance);
        }


        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'EventTime'
        /// </summary>
        [Test]
        public void EventTimeTest()
        {
            // TODO unit test for the property 'EventTime'
        }
        /// <summary>
        /// Test the property 'EventSourceUrl'
        /// </summary>
        [Test]
        public void EventSourceUrlTest()
        {
            // TODO unit test for the property 'EventSourceUrl'
        }
        /// <summary>
        /// Test the property 'OptOut'
        /// </summary>
        [Test]
        public void OptOutTest()
        {
            // TODO unit test for the property 'OptOut'
        }
        /// <summary>
        /// Test the property 'EventId'
        /// </summary>
        [Test]
        public void EventIdTest()
        {
            // TODO unit test for the property 'EventId'
        }
        /// <summary>
        /// Test the property 'ActionSource'
        /// </summary>
        [Test]
        public void ActionSourceTest()
        {
            // TODO unit test for the property 'ActionSource'
        }
        /// <summary>
        /// Test the property 'UserData'
        /// </summary>
        [Test]
        public void UserDataTest()
        {
            // TODO unit test for the property 'UserData'
        }
        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Test]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'DataProcessingOptions'
        /// </summary>
        [Test]
        public void DataProcessingOptionsTest()
        {
            // TODO unit test for the property 'DataProcessingOptions'
        }
        /// <summary>
        /// Test the property 'DataProcessingOptionsCountry'
        /// </summary>
        [Test]
        public void DataProcessingOptionsCountryTest()
        {
            // TODO unit test for the property 'DataProcessingOptionsCountry'
        }
        /// <summary>
        /// Test the property 'DataProcessingOptionsState'
        /// </summary>
        [Test]
        public void DataProcessingOptionsStateTest()
        {
            // TODO unit test for the property 'DataProcessingOptionsState'
        }

    }

}
