/*
 * Facebook Conversions API (for Web)
 *
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: web_signals_integrations@fb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SoundInTheory.Facebook.ConversionsAPI.Api;
using SoundInTheory.Facebook.ConversionsAPI.Model;
using SoundInTheory.Facebook.ConversionsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SoundInTheory.Facebook.ConversionsAPI.Test
{
    /// <summary>
    ///  Class for testing ResponseErrorError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseErrorErrorTests
    {
        // TODO uncomment below to declare an instance variable for ResponseErrorError
        //private ResponseErrorError instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseErrorError
            //instance = new ResponseErrorError();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseErrorError
        /// </summary>
        [Test]
        public void ResponseErrorErrorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ResponseErrorError
            //Assert.IsInstanceOf(typeof(ResponseErrorError), instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'FbtraceId'
        /// </summary>
        [Test]
        public void FbtraceIdTest()
        {
            // TODO unit test for the property 'FbtraceId'
        }
        /// <summary>
        /// Test the property 'ErrorSubcode'
        /// </summary>
        [Test]
        public void ErrorSubcodeTest()
        {
            // TODO unit test for the property 'ErrorSubcode'
        }
        /// <summary>
        /// Test the property 'IsTransient'
        /// </summary>
        [Test]
        public void IsTransientTest()
        {
            // TODO unit test for the property 'IsTransient'
        }
        /// <summary>
        /// Test the property 'ErrorUserTitle'
        /// </summary>
        [Test]
        public void ErrorUserTitleTest()
        {
            // TODO unit test for the property 'ErrorUserTitle'
        }
        /// <summary>
        /// Test the property 'ErrorUserMsg'
        /// </summary>
        [Test]
        public void ErrorUserMsgTest()
        {
            // TODO unit test for the property 'ErrorUserMsg'
        }

    }

}
