/*
 * Facebook Conversions API (for Web)
 *
 * The Conversions API (for web) allows advertisers to send web events from their servers directly to Facebook. Conversions API events are linked to a pixel and are processed like browser pixel events. This means that these conversion events are used in measurement, reporting, and optimization in the same way as browser pixel events.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: web_signals_integrations@fb.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SoundInTheory.Facebook.ConversionsAPI.Api;
using SoundInTheory.Facebook.ConversionsAPI.Model;
using SoundInTheory.Facebook.ConversionsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SoundInTheory.Facebook.ConversionsAPI.Test
{
    /// <summary>
    ///  Class for testing UserData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserDataTests
    {
        // TODO uncomment below to declare an instance variable for UserData
        //private UserData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserData
            //instance = new UserData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserData
        /// </summary>
        [Test]
        public void UserDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UserData
            //Assert.IsInstanceOf(typeof(UserData), instance);
        }


        /// <summary>
        /// Test the property 'Em'
        /// </summary>
        [Test]
        public void EmTest()
        {
            // TODO unit test for the property 'Em'
        }
        /// <summary>
        /// Test the property 'Ph'
        /// </summary>
        [Test]
        public void PhTest()
        {
            // TODO unit test for the property 'Ph'
        }
        /// <summary>
        /// Test the property 'Ge'
        /// </summary>
        [Test]
        public void GeTest()
        {
            // TODO unit test for the property 'Ge'
        }
        /// <summary>
        /// Test the property 'Db'
        /// </summary>
        [Test]
        public void DbTest()
        {
            // TODO unit test for the property 'Db'
        }
        /// <summary>
        /// Test the property 'Ln'
        /// </summary>
        [Test]
        public void LnTest()
        {
            // TODO unit test for the property 'Ln'
        }
        /// <summary>
        /// Test the property 'Fn'
        /// </summary>
        [Test]
        public void FnTest()
        {
            // TODO unit test for the property 'Fn'
        }
        /// <summary>
        /// Test the property 'Ct'
        /// </summary>
        [Test]
        public void CtTest()
        {
            // TODO unit test for the property 'Ct'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'St'
        /// </summary>
        [Test]
        public void StTest()
        {
            // TODO unit test for the property 'St'
        }
        /// <summary>
        /// Test the property 'Zp'
        /// </summary>
        [Test]
        public void ZpTest()
        {
            // TODO unit test for the property 'Zp'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'ClientIpAddress'
        /// </summary>
        [Test]
        public void ClientIpAddressTest()
        {
            // TODO unit test for the property 'ClientIpAddress'
        }
        /// <summary>
        /// Test the property 'ClientUserAgent'
        /// </summary>
        [Test]
        public void ClientUserAgentTest()
        {
            // TODO unit test for the property 'ClientUserAgent'
        }
        /// <summary>
        /// Test the property 'Fbc'
        /// </summary>
        [Test]
        public void FbcTest()
        {
            // TODO unit test for the property 'Fbc'
        }
        /// <summary>
        /// Test the property 'Fbp'
        /// </summary>
        [Test]
        public void FbpTest()
        {
            // TODO unit test for the property 'Fbp'
        }
        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Test]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }

    }

}
